//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer3.Core.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 客户端权限回收 的本地化字符串。
        /// </summary>
        public static string ClientPermissionsRevoked {
            get {
                return ResourceManager.GetString("ClientPermissionsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容安全政策 (CSP) 报告 的本地化字符串。
        /// </summary>
        public static string CspReport {
            get {
                return ResourceManager.GetString("CspReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部登录错误 的本地化字符串。
        /// </summary>
        public static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部登录失败 的本地化字符串。
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部登录成功 的本地化字符串。
        /// </summary>
        public static string ExternalLoginSuccess {
            get {
                return ResourceManager.GetString("ExternalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地登录失败 的本地化字符串。
        /// </summary>
        public static string LocalLoginFailure {
            get {
                return ResourceManager.GetString("LocalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地登录成功 的本地化字符串。
        /// </summary>
        public static string LocalLoginSuccess {
            get {
                return ResourceManager.GetString("LocalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销事件 的本地化字符串。
        /// </summary>
        public static string LogoutEvent {
            get {
                return ResourceManager.GetString("LogoutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分登录 的本地化字符串。
        /// </summary>
        public static string PartialLogin {
            get {
                return ResourceManager.GetString("PartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分登录完成 的本地化字符串。
        /// </summary>
        public static string PartialLoginComplete {
            get {
                return ResourceManager.GetString("PartialLoginComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预登陆失败 的本地化字符串。
        /// </summary>
        public static string PreLoginFailure {
            get {
                return ResourceManager.GetString("PreLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预登陆成功 的本地化字符串。
        /// </summary>
        public static string PreLoginSuccess {
            get {
                return ResourceManager.GetString("PreLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源所有者密码流程登录失败 的本地化字符串。
        /// </summary>
        public static string ResourceOwnerFlowLoginFailure {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源所有者密码流程登录成功 的本地化字符串。
        /// </summary>
        public static string ResourceOwnerFlowLoginSuccess {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginSuccess", resourceCulture);
            }
        }
    }
}
